[package]
name = "hello-world-rust"
version = "0.1.0"
authors = ["Alexander Kluth <deralex@cpan.org>"]
edition = "2018"

[dependencies]
gotham = "0.3.0"
tera = "0.11.20"
hyper = "0.12.17"
mime = "0.3.12"
lazy_static = "1.2.0"
